import "./globals.css";
import { Inter } from "next/font/google";
import ToasterContext from "../context/ToasterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Messenger app | MinhDuyDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterContext></ToasterContext>
        {children}
      </body>
    </html>
  );
}
// nHDUO5T9VC7aYCel
// mongodb+srv://minhduydev:<password>@cluster0.vpn5laa.mongodb.net/
// mongodb+srv://minhduydev:nHDUO5T9VC7aYCel@cluster0.vpn5laa.mongodb.net/messenger-app
